// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import {getWebGPUTestDevice} from '@luma.gl/test-utils';
import {expect, it} from 'vitest';
import {
  getGPUSegregationLayout,
  GPUSegregation
} from '../../../src/gpu-spatial-analysis/segregation/index';
import {expectClose, GraphRig} from '../areal-interpolation/areal-interpolation-harness';

/**
 * Reference values from PySAL `segregation` 2.6.0 (MultiInfoTheory, MultiDissim, Dissim,
 * Isolation, Atkinson with b = 0.5), generated by a 6x5 grid fixture. The spatial values are
 * PySAL's spatially implicit indices with libpysal Queen weights (binary, self weight 1), which
 * equal `spatialForm: 'smoothed-population'`.
 */
const COLUMNS = 6;
const ROWS = 5;
const GROUPS = 3;
// prettier-ignore
const COUNTS = [
  14, 10, 15, 44, 21, 18, 28, 11, 11, 21, 34, 25, 14, 13, 12, 10, 22, 16, 65, 10, 20, 55, 12, 18,
  42, 13, 18, 28, 34, 16, 12, 33, 14, 10, 31, 25, 56, 10, 19, 23, 15, 13, 33, 18, 16, 27, 24, 27,
  12, 45, 15, 10, 48, 18, 34, 10, 7, 44, 16, 22, 44, 26, 6, 17, 31, 10, 21, 55, 26, 10, 60, 8, 28,
  10, 23, 33, 11, 13, 21, 17, 9, 19, 26, 24, 19, 35, 16, 10, 63, 21
];
const PYSAL = {
  aspatial: {
    entropy: 0.10044802048604858,
    multiD: 0.29352154270822617,
    D: [0.35759738855131457, 0.34490080439710336, 0.14535469876573384],
    isolation: [0.48034847811858966, 0.46348532324064345, 0.2637671106502215],
    atkinson: [0.16442025001591698, 0.164249559426334, 0.04140243416945366]
  },
  queen: {
    entropy: 0.05884995629887694,
    multiD: 0.2196073138005297,
    D: [0.28870900521530907, 0.28480779130062295, 0.0446640855164301],
    isolation: [0.4555403465104299, 0.42707793055919924, 0.23945224815718044],
    atkinson: [0.10614177347066422, 0.10427765689905011, 0.0036721613550205756]
  }
};

function createQueenCSR() {
  const offsets = [0];
  const neighbors: number[] = [];
  for (let unit = 0; unit < COLUMNS * ROWS; unit++) {
    const column = unit % COLUMNS;
    const row = Math.floor(unit / COLUMNS);
    for (let other = 0; other < COLUMNS * ROWS; other++) {
      const dx = Math.abs((other % COLUMNS) - column);
      const dy = Math.abs(Math.floor(other / COLUMNS) - row);
      if (other !== unit && dx <= 1 && dy <= 1) neighbors.push(other);
    }
    offsets.push(neighbors.length);
  }
  return {offsets, neighbors};
}

it('GPUSegregation matches PySAL segregation (aspatial and queen-smoothed)', async () => {
  const device = await getWebGPUTestDevice();
  if (!device) return;
  const layout = getGPUSegregationLayout(GROUPS);
  const queen = createQueenCSR();
  const rig = new GraphRig(device);
  const indices = rig.output('float32', 2 * layout.stride);
  rig.run(
    new GPUSegregation({
      unitCount: COLUMNS * ROWS,
      groupCount: GROUPS,
      groupCounts: rig.input(Float32Array.from(COUNTS), 'float32'),
      scales: [
        null,
        {
          offsets: rig.input(Uint32Array.from(queen.offsets), 'uint32'),
          neighbors: rig.input(Uint32Array.from(queen.neighbors), 'uint32'),
          weights: rig.input(new Float32Array(queen.neighbors.length).fill(1), 'float32')
        }
      ],
      spatialForm: 'smoothed-population',
      indices: indices.view
    })
  );
  const result = await indices.readFloat32();
  rig.destroy();
  for (const [scale, reference] of [
    [0, PYSAL.aspatial],
    [1, PYSAL.queen]
  ] as const) {
    const row = result.slice(scale * layout.stride, (scale + 1) * layout.stride);
    const label = scale === 0 ? 'aspatial' : 'queen';
    expect(row[layout.entropy], `${label} entropy`).toBeGreaterThan(0.01);
    expectClose([row[layout.entropy]], [reference.entropy], `${label} entropy`, 2e-4, 1e-6);
    expectClose(
      [row[layout.multiGroupDissimilarity]],
      [reference.multiD],
      `${label} multiD`,
      2e-4,
      1e-6
    );
    expectClose(
      row.slice(layout.dissimilarity, layout.dissimilarity + 3),
      reference.D,
      `${label} D`,
      2e-4,
      1e-6
    );
    expectClose(
      row.slice(layout.isolation, layout.isolation + 3),
      reference.isolation,
      `${label} isolation`,
      2e-4,
      1e-6
    );
    expectClose(
      row.slice(layout.atkinson, layout.atkinson + 3),
      reference.atkinson,
      `${label} atkinson`,
      5e-3,
      1e-5
    );
  }
});
