// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import type {Buffer, Device} from '@luma.gl/core';
import {GPUCommandGraph} from '@luma.gl/gpgpu/gpu-core';
import {getWebGPUTestDevice} from '@luma.gl/test-utils';
import {expect, it} from 'vitest';
import {GPUParameterBuffer, importGraphBuffer} from '../../../src/utils/gpu-contributor-utils';
import {
  getGPUDotDensityParameterValues,
  GPURandomPointsOnLine,
  RANDOM_POINTS_ON_LINE_PURPOSE
} from '../../../src/gpu-spatial-analysis/dot-density/index';
import {
  getPhilox4x32,
  getPhiloxUnitFloat
} from '../../../src/gpu-spatial-analysis/dot-density/dot-density-random';
import {
  createInputBuffer,
  createOutputBuffer,
  readFloat32,
  readUint32,
  submitGraph
} from '../../utils/gpu-contributor-test-utils';

type Vertex = number[];

// Generated by shapely 2.1.2: `LineString(line).interpolate(u, normalized=True)` at
// `u = philox((line, rank, 0, 0), (7, 3))` (Philox 4x32-10 ported to Python; the spec also checks
// the TypeScript mirror against these fractions). Row: [line, rank, u, x, y].
const LINES: Vertex[][] = [
  [
    [0, 0],
    [3, 0],
    [3, 0],
    [3, 4],
    [10, 4]
  ],
  [
    [-5, -5],
    [5, 5]
  ],
  [[7, 7]],
  [
    [1, 1],
    [2, 1],
    [2, 2],
    [1, 2],
    [1, 1]
  ]
];
const COUNTS = [6, 4, 3, 5];
const SEED = 7;
const SHAPELY_POINTS: number[][] = [
  [0, 0, 0.20142346620559692, 2.819928527, 0.0],
  [0, 1, 0.20847898721694946, 2.918705821, 0.0],
  [0, 2, 0.09203100204467773, 1.288434029, 0.0],
  [0, 3, 0.812001645565033, 7.368023038, 4.0],
  [0, 4, 0.7535971999168396, 6.550360799, 4.0],
  [0, 5, 0.8078548312187195, 7.309967637, 4.0],
  [1, 0, 0.7283672094345093, 2.283672094, 2.283672094],
  [1, 1, 0.9679515957832336, 4.679515958, 4.679515958],
  [1, 2, 0.16371780633926392, -3.362821937, -3.362821937],
  [1, 3, 0.22562676668167114, -2.743732333, -2.743732333],
  [3, 0, 0.9969230890274048, 1.0, 1.012307644],
  [3, 1, 0.7358493804931641, 1.056602478, 2.0],
  [3, 2, 0.63053297996521, 1.47786808, 2.0],
  [3, 3, 0.8309198617935181, 1.0, 1.676320553],
  [3, 4, 0.5525326728820801, 1.789869308, 2.0]
];

type Result = {
  positions: number[];
  ids: number[];
  count: number;
  overflow: number;
  total: number;
  fractions: number[];
};

async function runRandomPoints(
  device: Device,
  lines: Vertex[][],
  counts: number[],
  capacity: number
): Promise<Result> {
  const flat = lines.flat();
  const offsets = [0];
  for (const line of lines) {
    offsets.push(offsets[offsets.length - 1] + line.length);
  }
  const graph = new GPUCommandGraph(device, {id: 'random-points-on-line'});
  const buffers: Buffer[] = [];
  const input = (
    id: string,
    values: Float32Array | Uint32Array,
    format: 'uint32' | 'float32x2'
  ) => {
    const buffer = createInputBuffer(device, values);
    buffers.push(buffer);
    return importGraphBuffer(
      graph,
      id,
      buffer,
      format,
      format === 'uint32' ? values.length : values.length / 2
    );
  };
  const output = (id: string, format: 'uint32' | 'float32' | 'float32x2', length: number) => {
    const buffer = createOutputBuffer(device, format === 'float32x2' ? length * 2 : length);
    buffers.push(buffer);
    return {buffer, view: importGraphBuffer(graph, id, buffer, format, length)};
  };
  const parameters = new GPUParameterBuffer(device, {
    id: 'parameters',
    format: 'uint32',
    length: 8
  });
  parameters.write(getGPUDotDensityParameterValues({seed: SEED}));
  const positions = output('positions', 'float32x2', capacity);
  const ids = output('ids', 'uint32', capacity);
  const count = output('count', 'uint32', 1);
  const overflow = output('overflow', 'uint32', 1);
  const total = output('total', 'uint32', 1);
  const fractions = output('fractions', 'float32', capacity);
  graph.add(
    new GPURandomPointsOnLine({
      id: 'points',
      positions: input('line-positions', Float32Array.from(flat.flat()), 'float32x2') as never,
      lineOffsets: input('line-offsets', Uint32Array.from(offsets), 'uint32') as never,
      counts: input('counts', Uint32Array.from(counts), 'uint32') as never,
      parameters: parameters.importToGraph(graph) as never,
      output: {
        positions: positions.view as never,
        points: {
          ids: ids.view as never,
          count: count.view as never,
          overflow: overflow.view as never,
          totalCount: total.view as never
        },
        fractions: fractions.view as never
      }
    })
  );
  const compiled = graph.compile();
  submitGraph(device, compiled, undefined);
  const result = {
    positions: await readFloat32(positions.buffer, capacity * 2),
    ids: await readUint32(ids.buffer, capacity),
    count: (await readUint32(count.buffer, 1))[0],
    overflow: (await readUint32(overflow.buffer, 1))[0],
    total: (await readUint32(total.buffer, 1))[0],
    fractions: await readFloat32(fractions.buffer, capacity)
  };
  compiled.destroy();
  parameters.destroy();
  for (const buffer of buffers) {
    buffer.destroy();
  }
  return result;
}

it('GPURandomPointsOnLine matches shapely interpolate at the Philox fractions', async () => {
  const device = await getWebGPUTestDevice();
  if (!device) {
    return;
  }
  const result = await runRandomPoints(device, LINES, COUNTS, 40);
  // The degenerate one-vertex line (line 2) draws no points.
  expect(result.count).toBe(15);
  expect(result.total).toBe(15);
  expect(result.overflow).toBe(0);
  expect(result.ids.slice(0, 15)).toEqual([
    ...Array(6).fill(0),
    ...Array(4).fill(1),
    ...Array(5).fill(3)
  ]);
  expect(result.ids[15]).toBe(0xffffffff);
  expect(Number.isNaN(result.positions[2 * 15])).toBe(true);
  expect(SHAPELY_POINTS.length).toBe(15);
  SHAPELY_POINTS.forEach(([line, rank, fraction, x, y], row) => {
    expect(result.ids[row]).toBe(line);
    // The TypeScript Philox mirror reproduces the pinned fraction exactly.
    const word = getPhilox4x32([line, rank, 0, 0], [SEED, RANDOM_POINTS_ON_LINE_PURPOSE])[0];
    expect(getPhiloxUnitFloat(word)).toBe(fraction);
    expect(result.fractions[row]).toBe(fraction);
    expect(Math.abs(result.positions[2 * row] - x)).toBeLessThan(2e-5 * (1 + Math.abs(x)));
    expect(Math.abs(result.positions[2 * row + 1] - y)).toBeLessThan(2e-5 * (1 + Math.abs(y)));
  });
});

it('GPURandomPointsOnLine keeps a stable prefix, flags overflow and samples uniformly', async () => {
  const device = await getWebGPUTestDevice();
  if (!device) {
    return;
  }
  const few = await runRandomPoints(device, LINES, [2, 2, 0, 2], 40);
  const many = await runRandomPoints(device, LINES, [6, 4, 0, 5], 40);
  // Raising a count only appends: ranks 0 and 1 of lines 0 and 1 keep their positions.
  expect(few.positions.slice(0, 4)).toEqual(many.positions.slice(0, 4));
  expect(few.positions.slice(4, 8)).toEqual(many.positions.slice(12, 16));
  const clipped = await runRandomPoints(device, LINES, COUNTS, 8);
  expect(clipped.count).toBe(8);
  expect(clipped.total).toBe(15);
  expect(clipped.overflow).toBe(1);
  expect(clipped.positions.slice(0, 16)).toEqual(many.positions.slice(0, 16));
  // Arc-length uniformity on a two-segment line of lengths 1 and 3.
  const line: Vertex[] = [
    [0, 0],
    [1, 0],
    [1, 3]
  ];
  const sampleCount = 4000;
  const uniform = await runRandomPoints(device, [line], [sampleCount], sampleCount);
  let onFirstSegment = 0;
  let fractionSum = 0;
  for (let row = 0; row < sampleCount; row++) {
    const x = uniform.positions[2 * row];
    const y = uniform.positions[2 * row + 1];
    expect(Math.min(Math.abs(y), Math.abs(x - 1))).toBeLessThan(1e-5);
    onFirstSegment += y < 1e-6 && x < 1 - 1e-6 ? 1 : 0;
    fractionSum += uniform.fractions[row];
  }
  expect(Math.abs(onFirstSegment / sampleCount - 0.25)).toBeLessThan(0.03);
  expect(Math.abs(fractionSum / sampleCount - 0.5)).toBeLessThan(0.02);
});
