// luma.gl
// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: Copyright (c) vis.gl contributors

import {Buffer, type Binding} from '@luma.gl/core';
import {Kernel} from '@luma.gl/engine';
import {
  createGPUComputeCommandNode,
  createTransientView,
  getBoundedDispatchLayout,
  getBoundedInvocationIndexSource,
  getViewBinding,
  getViewElementOffset,
  GraphVectorView,
  type GPUCommandGraph,
  type GPUCommandGraphGPUIndirectCondition,
  type GPUCommandGraphNodeCondition,
  type GPUCommandNode,
  type GraphBufferUse,
  type GraphDataView
} from '@luma.gl/gpgpu/gpu-core';
import type {GPUCompactOutput} from './gpu-contributor-types';

const DEFAULT_WORKGROUP_SIZE = 256;

/** GPU-written dispatch and its update node for a runtime active-item count. @internal */
export type WGSLActiveCountDispatch<Parameters> = {
  updateNode: GPUCommandNode<Parameters>;
  condition: GPUCommandGraphGPUIndirectCondition;
};

/**
 * Writes a bounded three-dimensional indirect dispatch from a GPU-resident item count.
 *
 * `invocationsPerItem` is one for ordinary linear kernels and equals the workgroup size for
 * cooperative one-workgroup-per-item kernels. The emitted dimensions preserve the static bounded
 * layout used by {@link createWGSLKernelNode}, so its linear invocation mapping remains valid.
 *
 * @internal
 */
export function createWGSLActiveCountDispatch<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    operation: string;
    count: GraphDataView<'uint32'>;
    countRow?: number;
    maximumItemCount: number;
    workgroupSize?: number;
    invocationsPerItem?: number;
    additionalInvocationCount?: number;
  }
): WGSLActiveCountDispatch<Parameters> {
  const workgroupSize = props.workgroupSize ?? DEFAULT_WORKGROUP_SIZE;
  const invocationsPerItem = props.invocationsPerItem ?? 1;
  const additionalInvocationCount = props.additionalInvocationCount ?? 0;
  const countRow = props.countRow ?? 0;
  if (
    !Number.isSafeInteger(countRow) ||
    countRow < 0 ||
    countRow >= props.count.length ||
    !Number.isSafeInteger(props.maximumItemCount) ||
    props.maximumItemCount < 0 ||
    !Number.isSafeInteger(invocationsPerItem) ||
    invocationsPerItem < 1 ||
    !Number.isSafeInteger(additionalInvocationCount) ||
    additionalInvocationCount < 0 ||
    props.maximumItemCount * invocationsPerItem + additionalInvocationCount > 0xffffffff
  ) {
    throw new Error(`${props.operation}: invalid active-count dispatch topology`);
  }
  const layout = getBoundedDispatchLayout(
    props.operation,
    Math.max(props.maximumItemCount * invocationsPerItem + additionalInvocationCount, 1),
    workgroupSize,
    graph.device.limits.maxComputeWorkgroupsPerDimension
  );
  const dispatch = createTransientView(
    graph,
    `${props.id}-buffer`,
    'uint32',
    3,
    Buffer.STORAGE | Buffer.INDIRECT
  );
  const updateNode = createWGSLKernelNode<Parameters>(graph, {
    id: props.id,
    operation: props.operation,
    variant: 'active-count-dispatch',
    bindings: [
      {name: 'count', view: props.count, type: 'u32', access: 'read'},
      {name: 'dispatch', view: dispatch, type: 'u32', access: 'read_write'}
    ],
    invocationCount: 1,
    workgroupSize: 2,
    declarations: `const COUNT_ROW: u32 = ${countRow}u;
const MAXIMUM_ITEM_COUNT: u32 = ${props.maximumItemCount}u;
const INVOCATIONS_PER_ITEM: u32 = ${invocationsPerItem}u;
const ADDITIONAL_INVOCATION_COUNT: u32 = ${additionalInvocationCount}u;
const TARGET_WORKGROUP_SIZE: u32 = ${workgroupSize}u;
const MAXIMUM_X: u32 = ${layout.x}u;
const MAXIMUM_Y: u32 = ${layout.y}u;`,
    body: `let itemCount = min(count[countOffset + COUNT_ROW], MAXIMUM_ITEM_COUNT);
  let invocationCount = itemCount * INVOCATIONS_PER_ITEM + ADDITIONAL_INVOCATION_COUNT;
  let workgroupCount = (invocationCount + TARGET_WORKGROUP_SIZE - 1u) / TARGET_WORKGROUP_SIZE;
  var x = min(workgroupCount, MAXIMUM_X);
  var y = 1u;
  var z = 1u;
  if (workgroupCount > MAXIMUM_X) {
    x = MAXIMUM_X;
    y = min((workgroupCount + MAXIMUM_X - 1u) / MAXIMUM_X, MAXIMUM_Y);
  }
  if (workgroupCount > MAXIMUM_X * MAXIMUM_Y) {
    y = MAXIMUM_Y;
    z = (workgroupCount + MAXIMUM_X * MAXIMUM_Y - 1u) / (MAXIMUM_X * MAXIMUM_Y);
  }
  dispatch[dispatchOffset] = x;
  dispatch[dispatchOffset + 1u] = y;
  dispatch[dispatchOffset + 2u] = z;`
  });
  return {
    updateNode,
    condition: {
      id: `${props.id}-condition`,
      source: 'gpu',
      mode: 'indirect',
      buffer: dispatch.buffer,
      byteOffset: dispatch.byteOffset
    }
  };
}
const MINIMUM_AUTOMATIC_WORKGROUP_SIZE = 32;

/** WGSL element type of one storage binding generated by {@link createWGSLKernelNode}. @internal */
export type WGSLKernelElementType = 'u32' | 'i32' | 'f32' | 'atomic<u32>' | 'atomic<i32>';

/** One storage binding of a generated WGSL kernel. @internal */
export type WGSLKernelBinding = {
  /** WGSL variable name. The generated `${name}Offset` constant holds the view's element offset. */
  name: string;
  /** Bound packed view. */
  view: GraphDataView;
  /** WGSL array element type. */
  type: WGSLKernelElementType;
  /** Storage access mode. */
  access: 'read' | 'read_write';
};

/** Properties for one linear WGSL compute kernel. @internal */
export type WGSLKernelProps<Parameters> = {
  /** Graph-wide node ID. */
  id: string;
  /** Operation name reported in the workload estimate, such as `GPUPointDensity`. */
  operation: string;
  /** Optional implementation variant reported in the workload estimate. */
  variant?: string;
  /** Storage bindings in `@binding` order. At most 8 for the WebGPU default limit. */
  bindings: readonly WGSLKernelBinding[];
  /** Number of linear invocations. Each invocation sees `index` in `[0, invocationCount)`. */
  invocationCount: number;
  /**
   * Power-of-two workgroup size. Guarded kernels choose 32, 64, 128, or 256 from the invocation
   * count. Cooperative kernels (`guardIndex: false`) retain 256 unless this is specified.
   */
  workgroupSize?: number;
  /** Module-scope WGSL declarations such as constants and helper functions. */
  declarations?: string;
  /** WGSL statements executed once per in-range `index`. */
  body: string;
  /**
   * When false, `body` runs for every dispatched invocation and must check
   * `index < INVOCATION_COUNT` itself. Use it for kernels with workgroup barriers. Default true.
   */
  guardIndex?: boolean;
  /** Optional node condition, for example a GPU-written indirect dispatch gate. */
  condition?: GPUCommandGraphNodeCondition<Parameters>;
  /** Additional declared resource uses, such as the `'indirect'` use of a condition buffer. */
  extraResources?: readonly GraphBufferUse[];
};

/**
 * Builds one compute node from bindings and a WGSL body, following the `GPUMask` pattern.
 *
 * Bindings use `getViewBinding` and expose `${name}Offset` WGSL constants. Every declared binding
 * is kept in the pipeline layout even when `body` never reads it, so callers may declare bindings
 * conditionally used by generated WGSL. Dispatch uses a bounded 3D layout so large inputs never
 * exceed `maxComputeWorkgroupsPerDimension`.
 *
 * @internal
 */
export function createWGSLKernelNode<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: WGSLKernelProps<Parameters>
): GPUCommandNode<Parameters> {
  const workgroupSize =
    props.workgroupSize ??
    (props.guardIndex === false
      ? DEFAULT_WORKGROUP_SIZE
      : getAutomaticWGSLKernelWorkgroupSize(props.invocationCount));
  // Fail at declaration, naming the kernel, instead of at pipeline creation. WebGPU's default is
  // 8 storage buffers per stage; devices created with higher limits accept more.
  const storageBufferLimit = graph.device.limits.maxStorageBuffersPerShaderStage;
  if (props.bindings.length > storageBufferLimit) {
    throw new Error(
      `${props.operation}: kernel ${props.id} binds ${props.bindings.length} storage buffers, ` +
        `more than the device limit of ${storageBufferLimit}`
    );
  }
  const layout = getBoundedDispatchLayout(
    props.operation,
    Math.max(props.invocationCount, 1),
    workgroupSize,
    graph.device.limits.maxComputeWorkgroupsPerDimension
  );
  const declarations = props.bindings
    .map(
      (
        binding,
        location
      ) => `const ${binding.name}Offset: u32 = ${getViewElementOffset(binding.view)}u;
@group(0) @binding(${location}) var<storage, ${binding.access}> ${binding.name}: array<${binding.type}>;`
    )
    .join('\n');
  // WebGPU `layout: 'auto'` only lists bindings the entry point statically uses, and a bind group
  // with an extra entry fails validation. A phony assignment of each binding's address is a
  // static use with no memory access, so every declared binding stays in the layout.
  const bindingReferences = props.bindings.map(binding => `_ = &${binding.name};`).join('\n  ');
  const source = /* wgsl */ `
override INVOCATION_COUNT: u32;
${declarations}
${props.declarations ?? ''}

@compute @workgroup_size(${workgroupSize})
fn main(
  @builtin(local_invocation_index) localInvocationIndex: u32,
  @builtin(workgroup_id) workgroupId: vec3<u32>
) {
  ${bindingReferences}
  ${getBoundedInvocationIndexSource(layout, workgroupSize)}
  ${props.guardIndex === false ? '' : 'if (index >= INVOCATION_COUNT) {\n    return;\n  }'}
  ${props.body}
}`;
  const resources: GraphBufferUse[] = props.bindings.map(binding => ({
    buffer: binding.view,
    usage: binding.access === 'read' ? 'storage-read' : 'storage-read-write'
  }));
  resources.push(...(props.extraResources ?? []));
  let readByteLength = 0;
  let writeByteLength = 0;
  for (const binding of props.bindings) {
    const byteLength = binding.view.length * binding.view.rowByteLength;
    if (binding.access === 'read') {
      readByteLength += byteLength;
    } else {
      writeByteLength += byteLength;
    }
  }
  return createGPUComputeCommandNode<Parameters>({
    id: props.id,
    resources,
    condition: props.condition,
    workload: {
      operation: props.operation,
      // GPUCommandGraph rejects a present-but-undefined variant.
      ...(props.variant ? {variant: props.variant} : {}),
      commandCount: 1,
      maximumWorkgroupCount: layout.x * layout.y * layout.z,
      maximumInvocationCount: props.invocationCount,
      readByteLength,
      writeByteLength
    },
    compile: ({device}) => {
      const kernel = new Kernel(device, {
        id: props.id,
        source,
        constants: {INVOCATION_COUNT: props.invocationCount},
        shaderLayout: {
          bindings: props.bindings.map((binding, location) => ({
            name: binding.name,
            type: binding.access === 'read' ? ('read-only-storage' as const) : ('storage' as const),
            group: 0,
            location
          }))
        }
      });
      let resolvedBuffers: Buffer[] = [];
      let resolvedBindings: Record<string, Binding> = {};
      let bindGroupCacheKey = {};
      return {
        encode: ({computePass, getBuffer}) => {
          const nextBuffers = props.bindings.map(binding => getBuffer(binding.view));
          const bindingsChanged = nextBuffers.some(
            (buffer, index) => buffer !== resolvedBuffers[index]
          );
          if (bindingsChanged || nextBuffers.length !== resolvedBuffers.length) {
            resolvedBuffers = nextBuffers;
            resolvedBindings = {};
            for (const [index, binding] of props.bindings.entries()) {
              const buffer = nextBuffers[index]!;
              resolvedBindings[binding.name] = getViewBinding(binding.view, () => buffer);
            }
            bindGroupCacheKey = {};
          }
          kernel.dispatch(computePass, {
            bindings: resolvedBindings,
            _bindGroupCacheKeys: {0: bindGroupCacheKey},
            x: layout.x,
            y: layout.y,
            z: layout.z
          });
        },
        destroy: () => kernel.destroy()
      };
    }
  });
}

/** Selects a warp-friendly workgroup without reserving 256 lanes for small guarded kernels. */
export function getAutomaticWGSLKernelWorkgroupSize(invocationCount: number): number {
  if (!Number.isSafeInteger(invocationCount) || invocationCount < 0) {
    throw new Error('WGSL kernel invocation count must be a non-negative safe integer');
  }
  const boundedCount = Math.max(invocationCount, MINIMUM_AUTOMATIC_WORKGROUP_SIZE);
  return Math.min(DEFAULT_WORKGROUP_SIZE, 2 ** Math.ceil(Math.log2(boundedCount)));
}

/** Formats a JS number as a WGSL `f32` literal. @internal */
export function getWGSLFloatLiteral(value: number): string {
  const float32Value = Math.fround(value);
  if (!Number.isFinite(float32Value)) {
    throw new Error('WGSL float literals must be finite');
  }
  if (Object.is(float32Value, -0)) {
    return '-0.0';
  }
  const text = String(float32Value);
  return /[.eE]/.test(text) ? text : `${text}.0`;
}

/**
 * Creates graph-owned `uint32` scratch rows with the same chunk topology as `template`.
 *
 * Unlike `createTransientVectorView`, the template may have any fixed-width format.
 *
 * @internal
 */
export function createTransientUint32Rows<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  id: string,
  template: GraphDataView | GraphVectorView
): GraphDataView<'uint32'> | GraphVectorView<'uint32'> {
  if (!(template instanceof GraphVectorView)) {
    return createTransientView(graph, id, 'uint32', template.length);
  }
  let emptyChunk: GraphDataView<'uint32'> | undefined;
  const data = template.data.map((chunk, chunkIndex) => {
    if (chunk.length === 0) {
      emptyChunk ??= createTransientView(graph, `${id}-empty`, 'uint32', 0);
      return emptyChunk;
    }
    return createTransientView(graph, `${id}-chunk-${chunkIndex}`, 'uint32', chunk.length);
  });
  return new GraphVectorView({
    id,
    name: id,
    format: 'uint32',
    length: template.length,
    valueLength: template.length,
    stride: 1,
    byteStride: 4,
    rowByteLength: 4,
    data
  });
}

/** Properties for {@link createPublishNode}. @internal */
export type PublishNodeProps = {
  /** Graph-wide node ID. */
  id: string;
  /** Operation name reported in the workload estimate. */
  operation: string;
  /** One-row unclamped accepted count written by an earlier compaction. */
  requiredCount: GraphDataView<'uint32'>;
  /**
   * Full-size compacted IDs to copy into `output.ids`. Omit when the compaction already wrote
   * `output.ids` directly.
   */
  compactIds?: GraphDataView<'uint32'>;
  /** Caller-owned bounded output. */
  output: GPUCompactOutput;
  /** Optional one-row flags ORed into `output.overflow`, for example index overflow. */
  overflowSources?: readonly GraphDataView<'uint32'>[];
  /** Additional packed one-row destinations that receive the clamped count. */
  extraCounts?: readonly GraphDataView<'uint32'>[];
  /**
   * Optional 32-bit column aligned with `compactIds` whose bounded prefix is copied verbatim into
   * `destination`, for example per-result priorities.
   */
  extraColumn?: {source: GraphDataView; destination: GraphDataView};
};

/**
 * Clamps an unclamped compaction count to the capacity of a {@link GPUCompactOutput}.
 *
 * Writes `count = min(total, capacity)`, `overflow = total > capacity || any overflow source`,
 * optional `requiredCount` and extra count words, and copies the bounded prefix when compaction used
 * a full-size scratch buffer. Every word is rewritten on every encoding.
 *
 * @internal
 */
export function createPublishNode<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: PublishNodeProps
): GPUCommandNode<Parameters> {
  const {output, compactIds} = props;
  const capacity = output.ids.length;
  const copyRowCount = compactIds ? Math.min(capacity, compactIds.length) : 0;
  const overflowSources = props.overflowSources ?? [];
  const extraCounts = props.extraCounts ?? [];
  const bindings: WGSLKernelBinding[] = [
    {name: 'totalIn', view: props.requiredCount, type: 'u32', access: 'read'}
  ];
  if (compactIds && copyRowCount > 0) {
    bindings.push({name: 'compactIn', view: compactIds, type: 'u32', access: 'read'});
    bindings.push({name: 'idsOut', view: output.ids, type: 'u32', access: 'read_write'});
  }
  for (const [sourceIndex, source] of overflowSources.entries()) {
    bindings.push({name: `overflowIn${sourceIndex}`, view: source, type: 'u32', access: 'read'});
  }
  bindings.push({name: 'countOut', view: output.count, type: 'u32', access: 'read_write'});
  bindings.push({name: 'overflowOut', view: output.overflow, type: 'u32', access: 'read_write'});
  if (output.requiredCount) {
    bindings.push({
      name: 'totalOut',
      view: output.requiredCount,
      type: 'u32',
      access: 'read_write'
    });
  }
  const extraColumn = copyRowCount > 0 ? props.extraColumn : undefined;
  if (extraColumn) {
    bindings.push(
      {name: 'columnIn', view: extraColumn.source, type: 'u32', access: 'read'},
      {name: 'columnOut', view: extraColumn.destination, type: 'u32', access: 'read_write'}
    );
  }
  for (const [extraIndex, extra] of extraCounts.entries()) {
    bindings.push({name: `extraOut${extraIndex}`, view: extra, type: 'u32', access: 'read_write'});
  }
  if (bindings.length > 8) {
    throw new Error(`${props.id} needs more than 8 storage bindings`);
  }
  const overflowExpression = [
    'total > CAPACITY',
    ...overflowSources.map(
      (_, sourceIndex) => `overflowIn${sourceIndex}[overflowIn${sourceIndex}Offset] != 0u`
    )
  ].join(' || ');
  return createWGSLKernelNode<Parameters>(graph, {
    id: props.id,
    operation: props.operation,
    variant: 'publish',
    bindings,
    invocationCount: Math.max(copyRowCount, 1),
    declarations: `const CAPACITY: u32 = ${capacity}u;
const COPY_ROW_COUNT: u32 = ${copyRowCount}u;`,
    body: `let total = totalIn[totalInOffset];
  let count = min(total, CAPACITY);
  ${
    copyRowCount > 0
      ? `if (index < COPY_ROW_COUNT && index < count) {
    idsOut[idsOutOffset + index] = compactIn[compactInOffset + index];
    ${extraColumn ? 'columnOut[columnOutOffset + index] = columnIn[columnInOffset + index];' : ''}
  }`
      : ''
  }
  if (index == 0u) {
    countOut[countOutOffset] = count;
    overflowOut[overflowOutOffset] = select(0u, 1u, ${overflowExpression});
    ${output.requiredCount ? 'totalOut[totalOutOffset] = total;' : ''}
    ${extraCounts.map((_, extraIndex) => `extraOut${extraIndex}[extraOut${extraIndex}Offset] = count;`).join('\n    ')}
  }`
  });
}

/**
 * Builds one node that fills `view` with a constant `u32`, `i32`, or `f32` value.
 *
 * @internal
 */
export function createFillNode<Parameters>(
  graph: GPUCommandGraph<Parameters>,
  props: {
    id: string;
    operation: string;
    view: GraphDataView;
    type: 'u32' | 'i32' | 'f32';
    value: string;
    componentCount?: number;
  }
): GPUCommandNode<Parameters> {
  const componentCount = props.componentCount ?? props.view.length;
  return createWGSLKernelNode<Parameters>(graph, {
    id: props.id,
    operation: props.operation,
    variant: 'fill',
    bindings: [{name: 'fillTarget', view: props.view, type: props.type, access: 'read_write'}],
    invocationCount: componentCount,
    body: `fillTarget[fillTargetOffset + index] = ${props.value};`
  });
}
